### ISSUE TITLE
Avro specification inside AsycnApi file

### ISSUE THREAD

**Issue by Lazzaretti** [asyncapi/spec#1015]
I'm unsure how, or if at all, Avro is supported inside the AsyncApi file or if you can only have it as a separate reference.

In version 2, I found examples of inline Avro definitions: https://github.com/asyncapi/avro-schema-parser?tab=readme-ov-file#usage

However, in version 3, I have not found any yet.
The specification states that for "Schema Object," you can only have JSON Schema Specifications. 

and

> Alternatively, any time a Schema Object can be used, a [Reference Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#referenceObject) can be used in its place. This allows referencing definitions in place of defining them inline. It is appropriate to clarify that the $ref keyword MUST follow the behavior described by [Reference Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#referenceObject) instead of the one in [JSON Schema definition](https://json-schema.org/understanding-json-schema/structuring.html#ref).

https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject

Is the assumption correct that Avro is not supported inline?
-> If so, it would be great to write that explicitly.
-> If it is supported, an example would be great!

### Describe the bug

Unclear behavior of how to add Avro schemas to AsycnApi .

### To Reproduce

Read the spec: https://www.asyncapi.com/docs/reference/specification/v3.0.0

### Additional context

AsyncAPI version 3.0.0

**Comment by smoya** [comment]
Hi @Lazzaretti !

v3 keeps the support for declaring an Avro schema without the need of a reference. The following example uses the one you linked but converted to v3 of the spec:

```yaml
asyncapi: 3.0.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    messages:
      myMessage:
        payload:
          schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
          schema:
            type: record
            name: User
            namespace: com.company
            doc: User information
            fields:
              - name: displayName
                type: string
              - name: email
                type: string
              - name: age
                type: int
```

[Open in Studio](https://studio.asyncapi.com/?base64=YXN5bmNhcGk6IDMuMC4wCmluZm86CiAgdGl0bGU6IEV4YW1wbGUgd2l0aCBBdnJvCiAgdmVyc2lvbjogMC4xLjAKY2hhbm5lbHM6CiAgZXhhbXBsZToKICAgIG1lc3NhZ2VzOgogICAgICBteU1lc3NhZ2U6CiAgICAgICAgcGF5bG9hZDoKICAgICAgICAgIHNjaGVtYUZvcm1hdDogJ2FwcGxpY2F0aW9uL3ZuZC5hcGFjaGUuYXZybzt2ZXJzaW9uPTEuOS4wJwogICAgICAgICAgc2NoZW1hOgogICAgICAgICAgICB0eXBlOiByZWNvcmQKICAgICAgICAgICAgbmFtZTogVXNlcgogICAgICAgICAgICBuYW1lc3BhY2U6IGNvbS5jb21wYW55CiAgICAgICAgICAgIGRvYzogVXNlciBpbmZvcm1hdGlvbgogICAgICAgICAgICBmaWVsZHM6CiAgICAgICAgICAgICAgLSBuYW1lOiBkaXNwbGF5TmFtZQogICAgICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgICAgLSBuYW1lOiBlbWFpbAogICAgICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgICAgLSBuYW1lOiBhZ2UKICAgICAgICAgICAgICAgIHR5cGU6IGludA%3D%3D)

Regarding your statements:

> The specification states that for "Schema Object," you can only have JSON Schema Specifications.

And that's true. The point is that the `payload` of a [Message Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#messageObject) can be now three different things:

![Google Chrome_etOrEJFg](https://github.com/asyncapi/spec/assets/1083296/241e39fb-0380-4417-9bfe-1ab222732ff7)

- [Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject), just AsyncAPI Schema type, superset of JSON Schema
- [MultiFormat Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#multiFormatSchemaObject) which supports several formats, including Avro.
- [Reference Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#referenceObject)

Note that the `schemaFormat` field is not anymore located in the Message Object but in the [MultiFormat Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#multiFormatSchemaObject). This allows reusing schemas in any part of your documents because it now includes the format they are written in.

After clarifying this, I can understand it might create confusion for those coming from pervious versions. We could include a statement in the [Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#schemaObject) saying something like "if you need support for other formats, please check the [MultiFormat Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#multiFormatSchemaObject) instead" (but with nice words 😅 ). 

Do you think that will improve the readability and understanding of that matter @Lazzaretti ?
