### ISSUE TITLE
Server Object host field compatibility with protocols

### ISSUE THREAD

**Issue by smoya** [asyncapi/spec#1016]
Recently we got a question [in our Slack](https://asyncapi.slack.com/archives/C0230UAM6R3/p1706705627052239) regarding a particularity on ibmqp binding. The question lead to checking that specifying a CCDT connection file should be possible in v3:

```yaml
asyncapi: 3.0.0
info:
  title: Test
  version: 0.1.0
servers:
  production1:
    host: 'http://my-ccdt-json-file/'
    protocol: ibmmq
  production2:
    host: 'file://myccdt.json/'
    protocol: ibmmq
```

As you can see, the `host` includes the protocol converting it to a URL, something I understand **not expected in v3** or even somehow illegal. The URL in rendered docs look like ibmmq://http://my-ccdt-json-file/ and ibmmq://file://myccdt.json/ respectively.

The question is, should a URL be allowed as a value for the `host` field? The spec doesn't mention anything about. Not even a "the `host` field should not be a URL".

Whatever direction we take, we should clarify what the host is expected or not to include.

Slack thread: https://asyncapi.slack.com/archives/C0230UAM6R3/p1706705627052239

**Comment by smoya** [comment]
cc @jonaslagoni @fmvilas @dalelane

**Comment by fmvilas** [comment]
Isn't it one of these cases where a subprotocol would work? For instance:

```yaml
asyncapi: 3.0.0
info:
  title: Test
  version: 0.1.0
servers:
  production1:
    host: 'my-ccdt-json-file/'
    protocol: ibmmq+http
  production2:
    host: 'myccdt.json/'
    protocol: ibmmq+file
```

To me, this is similar (if not the same) as with WebSocket + MQTT/STOMP/others.
