### ISSUE TITLE
[FEATURE REQUEST] Channel traits

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec#370]
**Is your feature request related to a problem? Please describe.**
While working on [ts-nats-template](https://github.com/asyncapi/ts-nats-template) I found the need to inherit bindings. I.e:
```
  smartylighting/streetlights/1/0/action/{streetlightId}/turn/on:
...
    traits:
      bindings:
        $ref: './components/channel-bindings.yml#/smartylightingTurnOn'
    bindings:
      nats:
        requestReply:
          is: requester
```

**Can't it be tackled using specification extensions?**
Yes, however I can see this as becoming a common use-case which would improve maintainability of one's AsyncAPI document.

**Describe the solution you'd like**
I can only see the bindings (maybe the description) as being part of the trait. 

**Describe alternatives you've considered**
This is exactly the use-case for traits as messages and operations are using it. Does not make sense to keep it at the extension level. We could add the `allOf` JSON Schema keyword, however that makes less sense IMO.
