### ISSUE TITLE
[FEATURE REQUEST] WAMP Server Binding

### ISSUE THREAD

**Issue by milgner** [asyncapi/spec#400]
In my current project I'd like to use AsyncAPI to describe an API that is served via WAMP.
After browsing https://www.asyncapi.com/docs/specifications/2.0.0/#serverBindingsObject I saw that although there are several protocol-specific binding schemas defined, WAMP isn't among them.

What I want to convey when specifying my WAMP server:
- connections are established via Websockets (WAMP subprotocol) on a specific URL
- the [WAMP realm](https://wamp-proto.org/_static/gen/wamp_latest.html#realms-sessions-and-transports) clients use when talking WAMP 

**Can't it be tackled using specification extensions?**
It seems to me like WAMP should be defined and on the same level as other protocols that are already available

**Describe the solution you'd like**
Using "wamp" as a protocol string works. Now just being able to specify a realm would be a good first step. Someone with more experience in WAMP might have more input.

```yaml
servers:
  staging:
    url: wss://example.com/my-wamp-handler
    protocol: wamp
    realm: com.example.wamp.asyncApi
    description: Staging Router
    security:
      - apiKey: []
```
