### ISSUE TITLE
Websocket Subprotocol Support

### ISSUE THREAD

**Issue by gexclaude** [asyncapi/spec#457]
**Is your feature request related to a problem? Please describe.**

In one of our applications, we use STOMP over WebSockets. As we want to make use of AsyncAPI in order to document this API we stumbled upon the lack of "subprotocol" support.

What is the "subprotocol" regarding WebSockets? A WebSocket connection is simply a connection. It can be used to tunnel almost anything, starting with things like plain text messages but also video streaming or database connections. See [IANA WebSocket Protocol for Subprotocols](https://www.iana.org/assignments/websocket/websocket.xml)

AsyncAPI allows setting a server protocol and protocol version. The protocol may be ws|wss for WebSocket or stomp|stomps for STOMP (https://www.asyncapi.com/docs/specifications/2.0.0#serverObject). A combination is not possible yet.

For WebSockets, it would be good to have a `subprotocol` field which would contain the WebSocket subprotocol identifier. For STOMP 1.2 this would be `v12.stomp` (according to IANA WebSocket Protocol Registries). A separation of `subprotocol` and `subprotocolVersion` could be an alternative, but I think it would not help.

**Can't it be tackled using specification extensions?**

This could be added to Websocket Binding.

**Describe the solution you'd like**

As described above I'd like a `subprotocol` field, most likely in the Websocket Binding.

**Describe alternatives you've considered**

**Additional context**

**Comment by gexclaude** [comment]
My proposals would be

1. One field `subprotocol` using the subprotocol identifiers mentioned above

```yaml
servers:
  dev:
    url: someurl.com/websocket
    description: Development Cluster
    protocol: wss
    protocolVersion: "13"
    subprotocol: v12.stomp	
```

2. Two field `subprotocol` and `subprotocolVersion` following the `protocol` and `protocolVersion` pattern
```yaml
servers:
  dev:
    url: someurl.com/websocket
    description: Development Cluster
    protocol: wss
    protocolVersion: "13"
    subprotocol: stomp
    subprotocolVersion: "12"
```

3. Using websocket binding with only one field `subprotocol` using subprotocol identifiers mentioned above
```yaml
servers:
  dev:
    url: someurl.com/websocket
    description: Development Cluster
    protocol: wss
    protocolVersion: "13"
    bindings:
        ws:
            subprotocol: v12.stomp
```

to me it would make sense to go with 2 (general solution) or 3 (websocket specific solution).

What do you think?
