### ISSUE TITLE
Add security mechanism info to Kafka bindings for server objects

### ISSUE THREAD

**Issue by dalelane** [asyncapi/spec#466]
**Is your feature request related to a problem? Please describe.**
Kafka has several values that are essential to know when preparing to connect to a secured Kafka cluster, such as `sasl.mechanism` and `security.protocol`. Adding these to the Kafka binding for server objects would allow these to be documented.

**Can't it be tackled using specification extensions?**
It could be captured in extensions.

e.g.
```
asyncapi: '2.0.0'
...
servers:
  production:
    url: localhost:9092
    protocol: kafka-secure
    security:
    - saslScramCreds: []
...
components:
  securitySchemes:
    saslScramCreds:
      type: userPassword
      x-mykafka-sasl-mechanism: 'SCRAM-SHA-256'
      x-mykafka-security-protocol: 'SASL_SSL'
```

However I think this is a common enough request that there would be value in doing it in a consistent way. In particular, it would enable code generation to set up the right Kafka client properties.

**Describe the solution you'd like**
Strawman suggestion:
```
asyncapi: '2.0.0'
...
servers:
  production:
    url: localhost:9092
    protocol: kafka-secure
    security:
    - saslScramCreds: []
    bindings:
      kafka:
        saslMechanism: 'SCRAM-SHA-256'
        securityProtocol: 'SASL_SSL'
...
components:
  securitySchemes:
    saslScramCreds:
      type: userPassword
```

**Describe alternatives you've considered**
Fran Méndez [suggested](https://asyncapi.slack.com/archives/C34F2JV0U/p1606406595418100?thread_ts=1606403605.417600&cid=C34F2JV0U): 
> We should make it part of the security schemes, it's not only for Kafka after all.

**Comment by magicmatatjahu** [comment]
I wonder if adding another security mechanism to the AsyncAPI JSON Schema it makes sense in the long term. I mean looking at this table https://github.com/asyncapi/bindings/pull/56#issuecomment-785834586 I have this problem that we may forget something and will have to tweak it in the AsyncAPI scheme and publish new version etc. Would treating `securityScheme` as extension cause problems in long term? I mean extension like:

```yaml
id: saslSecurityScheme
type: securityScheme # new type of extension
title: ...
...

components:
  securitySchemes:
    usingSaslSecurityScheme
       type: saslSecurityScheme
       ...
```

I am aware that the above schema is not fully correct, but I hope that the idea itself is understandable.

@fmvilas @derberg @jonaslagoni @smoya @dalelane Any thoughts?
