### ISSUE TITLE
Add "channelContext" property to server object

### ISSUE THREAD

**Issue by 195858** [asyncapi/spec#527]
The suggestion is to add a `channelContext` property to the "Server Object".

The motivation is the following use case:
Organisation has a number of logical stages that artifacts are propagated through.
- Dev
- QA
- UA
- Staging 
- Prod

However the physical infrastructure consists of  shared brokers for Dev, QA, UA.
This means we need to have a dedicated root namespace for each environment on this shared infrastructure ...

Consider the channel is called `smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured` - in the shared environment the actual topics that is supposed to be used must be prefixed e.g. `dev/smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured`
We need to be able to describe the actual topics in the Async API spec without changing the channel description.

The logical place to put it seems to be the "Server Object" so clients can easily switch between environments without changes to the channel definitions.
Here's an example of how it could look like:
```
servers:
  qa:
    url: mqtt://xxxyyyzzz.messaging.solace.cloud:1833
    channelContext: qa
    protocol: mqtt
    description: Solace broker
```
Code generators or the generated code can prepend the `channelContext` to all channels and a developer can switch between environments easily by using a different server endpoint.
