### ISSUE TITLE
Avro schemas are not supported in the components/schemas section

### ISSUE THREAD

**Issue by MichaelDavisSolace** [asyncapi/spec#528]
### Describe the bug
Asyncapi supports Avro schemas, but only if they are in the message/payload section. It would be nice if we could put Avro schemas in the components/schemas section.

### To Reproduce
1. Create a document with an Avro schema in components/schemas. It will fail in the playground.

### Expected behavior
The document should parse as it does when the schema is in the message/payload section.

### Sample document
asyncapi: 2.0.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload:
          $ref: '#components/schemas/mySchema'
components:
  schemas:
    mySchema:
      type: record
      doc: User information
      fields:
        - name: displayName
          type: string

**Comment by magicmatatjahu** [comment]
Thanks for the issue!

The problem as I see is that currently `schemaFormat` can only be used for `payload`. Using `schemaFormat` in schemas would entail creating something like this: 

```yaml
components:
  schemas:
    mySchema:
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      schema:
        type: record
        doc: User information
        fields:
          - name: displayName
            type: string
```

The solution for me is bad (in sense of user experience) because then user would have to write something like this if he wanted to refer to schema:

```yaml
payload:
  $ref: '#components/schemas/mySchema/schema'
```

Another suggestion would be to use a map for custom schemaFormats:

```yaml
components:

  schemaFormats:
    mySchema: 'application/vnd.apache.avro;version=1.9.0'
    
  schemas:
    mySchema:
      type: record
      doc: User information
      fields:
        - name: displayName
          type: string
```

TBH I don't know how it can be handled in proper way. Let's wait for other people and their insights :)

**Comment by magicmatatjahu** [comment]
I thought a little more about problem and the `schemaFormat` inside the schema shouldn't cause any problems:

```yaml
components:
  schemas:
    mySchema:
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      type: record
      doc: User information
      fields:
        - name: displayName
          type: string
```

By default it will be JSON/Schema (aka AsyncAPI Schema) and in the tooling we can parse and validate schemas using `schemaFormat`.

**Comment by MichaelDavisSolace** [comment]
Yes, I like that.

**Comment by magicmatatjahu** [comment]
Also we can add to the spec `defaultSchemaFormat` field in root, with functionality very similar like `defaultContentType` to determine the global `schemaType` and then the user would not have to specify the type (like avro) every time if wants to use it in all schemas.

```yaml
asyncapi: 2.0.0
info: ...

defaultSchemaType: 'application/vnd.apache.avro;version=1.9.0'

components:
  schemas:
    mySchema:
      type: record
      doc: User information
      fields:
        - name: displayName
          type: string
```
