### ISSUE TITLE
Replace server.url with server.host

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/spec#547]
### Problem

Currently, AsyncAPI servers have a property called `url`. In many cases, we're showing examples of the `url` field as a host instead (without the protocol part of the URL) which is incorrect. On top of that, what's the point of having the protocol included in the `url` field if we already have the `protocol` field? This is an example of what I'm talking about:

```yaml
asyncapi: 3.0.0
servers:
  localhost:
    url: mqtt://localhost
    protocol: mqtt
  production:
    url: kafka://my-production-server.com
    protocol: kafka
```

It can also create inconsistencies where the protocol in the URL and the `protocol` field don't match:

```yaml
asyncapi: 3.0.0
servers:
  localhost:
    url: kafka://localhost
    protocol: mqtt
```

### Proposal

My proposal is that we rename the `url` field as `host`, which would be more correct. Example:

```yaml
asyncapi: 3.0.0
servers:
  localhost:
    host: localhost
    protocol: mqtt
  production:
    host: my-production-server.com
    protocol: kafka
```

---

We may also have to consider adding other parts of the URL like the path and query variables.

This is a proposal to fix #274
