### ISSUE TITLE
Support callback message descriptions

### ISSUE THREAD

**Issue by ghost** [asyncapi/spec#55]
Right now, AsyncAPI does not specify how callback messages should be described. 

Some ad-hoc approaches can be used. For instance:
- a topic.publish request's callback message can be described on topic.subscribe (even though it will probably not be conveyed through 'topic')
- a topic.subscribe operation's callback message can be described on topic.publish (even though it will probably not be conveyed through 'topic')
- a separate callback topic can be described (e.g., using Topic Templating as required), together with the message 

Hence, for convenience and clarity reasons, a structural callback-specification approach similar to the one proposed in OpenAPIv3 (cfr. [spec ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#callbackObject)+ [example](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/callback-example.yaml)) might be interesting for AsyncAPI as well?

It could look like this:

```
topics:
  UPDATEARTICLE:
    publish:
      headers:
        type: object
        properties:
          reply-to:
            type: string
            description: Callback Destination to be messaged when the Article was updated
          correlation-id:
            $ref : '#/components/schemas/Correlation-id'
      payload:
        type: object
        properties:
          ...
      callbacks:
        reply:
          '{$request.header.reply-to}':
            publish:
              summary: Reply sent through callback
              headers:
                type: object
                properties:
                  correlation-id:
                    $ref : '#/components/schemas/Correlation-id'          
              payload:
                  type: object
                  properties:
                    success:
                      type: boolean
                    statusMsg:
                      type: string 
```

Thanks in advance for considering this feature request!
