### ISSUE TITLE
Establish a mechanism for bindings specs to contribute schema objects for protocol headers

### ISSUE THREAD

**Issue by GeraldLoeffler** [asyncapi/spec#555]
The consensus in bindings specs is for protocol headers (= well-known message headers defined by the server's protocol (HTTP, JMS, Anypoint MQ, ...) rather than by the message sender) to be defined in the `headers` field of the message binding object as schema objects. See for example the [HTTP message binding object](https://github.com/asyncapi/bindings/tree/master/http#message-binding-object).

But this means that every AsyncAPI document using protocol headers is likely to define a schema object for some of the same well-known protocol headers. For example, for the HTTP protocol headers, an AsyncAPI document might use

```
message:
  bindings:
    http:
      headers:
        type: object
          properties:
            Content-Type:
              type: string
            Date:
              type: string
              pattern: "complex regex for RFC 7231 Date/Time Format"
            Accept-Charset:
              type: string
            ...
```

and something similar will be repeated in other AsyncAPI documents using the HTTP binding.

To reduce duplication and boilerplate, AsyncAPI binding specification should have a mechanism to provide schema objects for well-known protocol headers. AsyncAPI docs would then just reference these provided schema objects, instead of having to define their own schema objects.
