### ISSUE TITLE
Understanding WebSocket API descriptions

### ISSUE THREAD

**Issue by bali182** [asyncapi/spec#570]
Hello, I'm raising this issue  to have a better understanding how the ws protocol is described. I'm looking at this example: 

https://github.com/asyncapi/spec/blob/master/examples/2.0.0/websocket-gemini.yml

1. When using websockets, the keys in `Channels Object` are the URLs to connect to right?  So this:
```yaml
channels:
  /v1/marketdata/{symbol}:
```

Would mean connect to this URI (where symbol is a parameter), right?:
```ts
//                  in servers              in the channel
new WebSocket("wss://api.gemini.com" + "/v1/marketdata/{symbol}")
```

If we have multiple entries in the `Channels Object` does that mean we can connect to multiple endpoints with their respective parameters and available subscriptions/publishes?

2. What is query under ws bindings? Is that something that has to be turned into a query string when establishing the connection? So this:

```yaml
query:
  type: object
  properties:
    heartbeat:
      type: boolean
      default: false
    top_of_book:
      type: boolean
      default: false
    bids:
      type: boolean
      default: true
    ...
```
Would also go into the URI?
```ts
new WebSocket("wss://api.gemini.com" + "/v1/marketdata/{symbol}?heartbeat=...&top_of_book=...")
```
In case yes, how to serialize the fields of this object? I saw that it must be an object with properties in the docs, but can the properties objects themselves? If so how deeply nested can this structure go and what would be the serialization method for it? OpenAPI has a nightmarish amount of parameter serialization methods, I hope you went with a simpler approach :D

In case I'm completely wrong please advise!

**Comment by derberg** [comment]
Hey @bali182 

> If we have multiple entries in the Channels Object does that mean we can connect to multiple endpoints with their respective parameters and available subscriptions/publishes?

yes, it means you have have multiple connections with the server. Have a look at [this](https://github.com/derberg/shrekapp-asyncapi-designed) example I've build with one of our code generators.

> What is query under ws bindings? Is that something that has to be turned into a query string when establishing the connection

exactly. You have few examples in official Gemini docs https://docs.gemini.com/websocket-api/#market-data


> but can the properties objects themselves

what do you mean?

> If so how deeply nested can this structure go

in the end it describes a list of available query params. The question is how complex can this get. For me it is always flat. This means one level, no nesting. Can be, as I used, object type JSON Schema, but you can go with array too if you think it is better

**Comment by bali182** [comment]
Hey @derberg thanks for getting back to me! Let me elaborate what I meant by parameter serialization. 

OpenAPI describes parameter serialization here: https://swagger.io/docs/specification/serialization/

It basically says parameters can be primitive types (string, number or boolean) or 1 level, non nested objects or arrays. 

What I'm asking here is if there is a nested object or array schema for the schema of the path or query parameters, for example

Nested object (invalid according to OpenAPI spec):

```
query:
  type: object
  properties:
    heartbeat:
      type: object
      properties:
        foo:
          type: object
          properties:
            ... so on
```

Nested array (invalid according to OpenAPI spec):

```
query:
  type: object
  properties:
    heartbeat:
      type: array
      items:
        type: object
        properties:
          foo: 
            type: array
            items: 
              type: string
```

Is this valid according to AsyncAPI spec, or not, and if it is what's the protocol for serializing and deserializing these in query/path? 

Since there is no `style` option for parameters, like OpenAPI, I assumed there is only one format for each, but for tools its kinda important to know what that format is.

Thank you, 
Balazs

**Comment by derberg** [comment]
At the moment, this specific binding information is described in the WebSocket binding spec -> https://github.com/asyncapi/bindings/tree/master/websockets

So the schema must be of `type: object` and have `properties` key. The Gemini example that I provided shows a non nested flat structure. For me the example that you provided is already nested:

```
query:
  type: object
  properties:
    heartbeat:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: number
```

it is object in object.

Does it even make sense from technical point of view? I mean, how would the resulting query param look like for such example?


---- 
I movie this issue to binding repo as it is discussion about the binding
