### ISSUE TITLE
Allow grouping of servers by stage/environment

### ISSUE THREAD

**Issue by gervaisb** [asyncapi/spec#65]
It is common to have many servers for the same stage (dev, test, acc, ..), the variable substitutions into the server object can help but the substitution can also be problematic when there is some restriction on what can be substituted. 
A solution is to create different servers however, there is nothing to group them and to restrict the usage of servers from different stages.
I can be interesting to have a `group` attribute in server:

**Configuration:**
+ dev-master-1:1234
+ dev-master-2:1234
+ dev-slave-1:4321
+ dev-slave-2:4321
+ test-master-1:1234
+ test-master-2:1234
+ test-slave-1:4321
+ test-slave-2:4321

**Current:**
```
servers:
  - url: dev-master-{node}:1234
    variables:
      node:
        enum:
          - '1'
          - '2'
  - url: dev-slave-{node}:4321
    variables:
      node:
        enum:
          - '1'
          - '2'
  - url: test-master-{node}:1234
    variables:
      node:
        enum:
          - '1'
          - '2'
  - url: test-slave-{node}:4321
    variables:
      node:
        enum:
          - '1'
          - '2'
```

**Proposal:**
```
servers:
  - url: dev-master-{node}:1234
    group: dev
    variables:
      node:
        enum:
          - '1'
          - '2'
  - url: dev-slave-{node}:4321
    group: dev
    variables:
      node:
        enum:
          - '1'
          - '2'
  - url: test-master-{node}:1234
    group: test
    variables:
      node:
        enum:
          - '1'
          - '2'
  - url: test-slave-{node}:4321
    group: test
    variables:
      node:
        enum:
          - '1'
          - '2'
