### ISSUE TITLE
`example` is used for example for Schema Object examples (instead of `examples`)

### ISSUE THREAD

**Issue by aborg0** [asyncapi/spec#698]
### Describe the bug
At [Schema Object examples Model with Example](https://www.asyncapi.com/docs/specifications/v2.2.0#model-with-example) the examples (JSON and also the YAML) use `example`, but the previous part of the specification suggests that `examples` can be used. The tooling seems to support `examples`, but not `example`.
Discussion: https://asyncapi.slack.com/archives/CQVJXFNQL/p1642787250166800

### To Reproduce
1. Create a document with `example`.
2. Try to change to 'examples' and make it a list.
3. Try to validate the document doing 'studio' for example
4. The studio does not render the `example`, but it does the `examples`

### Expected behavior
I expect to support examples (/), and at least does not provide an example with `example`, maybe that can be disallowed in the spec too to avoid confusion (though that can be hard to defend as the schema can have extra keys).

### Sample document
Example fragmentss I think we should not have:
```
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "name"
  ],
  "example": {
    "name": "Puma",
    "id": 1
  }
}
```
```
type: object
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
required:
- name
example:
  name: Puma
  id: 1
```
Proper example fragments should look like this in my opinion:
```
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "name"
  ],
  "examples": [
     {
       "name": "Puma",
       "id": 1
     }
  ]
}
```
```
type: object
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
required:
- name
examples:
  -
    name: Puma
    id: 1
```
