### ISSUE TITLE
Expanded tags support: allow adding tags to more entities, support refs

### ISSUE THREAD

**Issue by gabormagyar** [asyncapi/spec#750]
Tags are great! I see two low hanging improvements that could be made to them:

### Refs

Tags could be added under `components`, and could be referenced in other places so that tags (potentially with documentation and info links) don't have to be duplicated across usages

### More entities

I tried to add tags to schemas, but the parser told me that that was invalid. I see no reason to disallow this. Should probably consider other places where tags may be applicable.

Relevant slack thread with @magicmatatjahu: https://asyncapi.slack.com/archives/CQVJXFNQL/p1649332581535119

**Comment by derberg** [comment]
@gabormagyar can you specify where exactly you would like to see `Tag` object enabled, and share example?
Because we do releases regularly we always try to add things only that have use case rather that assuming use case 😄 I guess you know what I mean.

I also understand you'd like to have it also in components so it can be refed from other parts of the document

**Comment by gabormagyar** [comment]
Right now I have most of my channels looking like this:

```yaml
subscribe:
  message:
    payload:
      $ref: @schemas/payload.yml
publish:
  description: Description
  message:
    payload:
      $ref: @schemas/payload.yml
tags:
  - {{ mixin('@tags/producer-driven.yml.njk') }}
```

`mixin` is provided by [boats](https://www.npmjs.com/package/boats), and I do a separate postprocess step on the final yaml to take the top level tags and copy them into the publish and subscribe operations. My output looks like this:

```yaml
subscribe:
  message:
    payload:
      $ref: ../../../components/schemas/payload.yml
  tags:
    - name: tag-name
      description: >-
        Tag description
      externalDocs:
        description: More info
        url: >-
          https://github.com/.../README.md
publish:
  description: Description
  message:
    payload:
      $ref: ../../../components/schemas/payload.yml
  tags:
    - name: tag-name
      description: >-
        Tag description
      externalDocs:
        description: More info
        url: >-
          https://github.com/.../README.md
```
