### ISSUE TITLE
Can a full REST API, assume all the HTTP Methods are used, for a single URL be documented?

### ISSUE THREAD

**Issue by upsampled** [asyncapi/spec#813]
I like AsyncAPI because it embraces multiple protocols, specifically websockets which i use often. The problem is that I still have the document the legacy REST APIs in order to extend them and I cannot document all the HTTP Methods they support.

```yml
  /v1/bus:
    description: involves requesting an action be performed on a bus
    servers: ['LegacyREST']
    subscribe:
      bindings:
        http:
          type: request
          method: GET
          query:
            $ref: './query.yml#/bus'
      message:
        $ref: './message.yml#/bus'
    publish:
        bindings:
          http:
            type: request
            method: PUT
            query:
              $ref: './message.yml#/bus'
```

Right now I have only been able to assign one HTTP method to subscribe and publish. Subscribe can probably just stay associated with GET, but publish really needs to be associated with PUT, POST, PATCH, DELETE. I realize you can try to get around the two method restriction with REST call that have arguments in the URL (IE: `/v1/bus/{id}`), but that doesn't help me if I am documenting an API that was already created with only query arguments.
