### ISSUE TITLE
[Feature Request] Support $ref list in channels and components definition

### ISSUE THREAD

**Issue by TheLand** [asyncapi/spec#820]
Hi all,

could be useful to get files YAML and the documentation better organized adding the possibility to link to multiple files in `channels` and `components` sections using the **$ref** special key.

Now I have to declare the main `asyncapi.yaml` file 
```
channels:
  chatusers.get:
    $ref: "./ChatUsers.yaml#/channels/chatusers.get"
  chatusers.get-vars:
    $ref: "./ChatUsers.yaml#/channels/chatusers.get-vars"
  chatusers.delete:
    $ref: "./ChatUsers.yaml#/channels/chatusers.delete"
  chatusers.insights:
    $ref: "./ChatUsers.yaml#/channels/chatusers.insights"
```

But if I could make something like:
```
channels:
  - $ref: "./ChatUsers.yaml#/channels"
  - $ref: "./AutomatedMessages.yaml#/channels"
```
It would be better i think: the main file would stay clean and limited and all specifications stay in their named files.
It isn't a breaking change: you could support the old style and this new style.

Hope it's clear.
