### ISSUE TITLE
[3.0.0] Should `description` fields be able to be referenced?

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/spec#868]
Currently, we cannot refer to markdown content from external files in our specification. We currently have to add description to the spec itself without the ability to reference. If the content itself is large and it would be easier to keep the markdown in a separate file, it would make life easier for many people. Hence my question, should we allow referencing in `description` fields?

Personally, I think so, but we need to keep in mind the problems on the tooling side - not every tooling that make dereferencing supports references to non JSON/YAML objects.

**Comment by char0n** [comment]
IMHO it depends. Are there many definition authors requesting this? Do definition authors consider inability to reference a description to be an issue?

### Internal sharing

Internal sharing can be achieved by native YAML features like: **anchoring**

```yaml
---
title: AsyncAPI Sample App
description: *shared_desc
termsOfService: https://asyncapi.org/terms/
contact:
  name: API Support
  url: https://www.asyncapi.org/support
  email: support@asyncapi.org
license:
  name: Apache 2.0
  url: https://www.apache.org/licenses/LICENSE-2.0.html
version: 1.0.1
```

### External sharing

If I wanted to keep huge markdown content and transclude it to my AsyncAPI definition, this can be achieved by simple transformation of AsyncAPI definition document before publishing it. I do think that this is actually an issue of definition composition phase, rather then runtime referencing issue. 

When publishing my AsyncAPI definition, I would have to make the markdown file publicly available as well so that the AsyncAPI definition has access to it during runtime in order to dereference it.
