### ISSUE TITLE
Add official XSD schema format

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec#915]
**Description**

We discussed this in the following meeting: https://www.youtube.com/watch?v=8Yjles2pEHo

It would be nice to have official schemaFormat types for XSD, so all tooling can understand when XSD is in use instead of each having using it's own.

I have no specific suggestion for the value it self, that needs to be researched.

**Comment by derberg** [comment]
@jessemenning @damaru-inc you are the only ones I know in the community that advocated for XSD in the past. So maybe you can help define those

**Comment by GreenRover** [comment]
I struggle again about this issue and i am not sure if there is any beautiful solution to map this xml example:

```xml

<outer attributeA="foo" attributeB=12>
  <inner>the first</inner>
  <inner>the second</inner>
  <inner>the third</inner>
  <innerB>the first</innerB>
<outer>
```

to json schema the parser.js internal model.
At leased something like:

```yaml
properties:
  attributeA:
    type: string
  attributeB
    type: integer
  innerA:
    type: array
	items:
	  type: string
  innerB:
    type: string
```

Than it is not clear that `attributeA` and `attributeB` are xml attributes
and `innerA` , `innerB` are child nodes.

To support this we need to enhance json schema some how.
