### ISSUE TITLE
How to handle Bearer Authentication using a JMS Header?

### ISSUE THREAD

**Issue by adamretter** [asyncapi/spec#920]
The `securitySchemes` mechanism of AsyncAPI 2.6.0 spec does not seem compatible with the idea of sending an Auth token (e.g. similar to Bearer Authentication) in a header when using the JMS protocol. The 2.6.0 version of the spec seems to restrict this to HTTP only for some reason.

I would like to be able to achieve something like:

```yaml
securitySchemes:
  bearerAuthentication:
    type: apiKey
    in: header
    name: AuthenticationToken
    description: Bearer Authentication Token should be provided in the `AuthenticationToken` header.
```

Thoughts on how I can achieve this, or should I contribute an update to the spec?
