### ISSUE TITLE
update release workflow in release branch

### ISSUE THREAD

**Issue by derberg** [asyncapi/spec#938]
Release https://github.com/asyncapi/spec/blob/next-major-spec/.github/workflows/release.yml needs update

Because of https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

```yml
      - name: Setup Node.js
        uses: actions/setup-node@v1
```

needs to be replaced with
```yml
- name: Setup Node.js
   uses: actions/setup-node@v3
   with:
      node-version: 18
```

also 
```
npm install conventional-changelog-conventionalcommits
```

update to
```
npm install --save-dev conventional-changelog-conventionalcommits@5.0.0
```

and switch:
```
actions/checkout@v2
```

to 
```
actions/checkout@v3
```
